
import { GoogleGenAI, Type, Schema } from "@google/genai";
import { TextAnalysisResult } from "../types";

const TEXT_ANALYSIS_SCHEMA: Schema = {
  type: Type.OBJECT,
  properties: {
    score: {
      type: Type.NUMBER,
      description: "Probability score from 0.0 (Human) to 1.0 (AI).",
    },
    label: {
      type: Type.STRING,
      enum: ["human", "ai", "uncertain"],
      description: "Classification label.",
    },
    confidence: {
      type: Type.NUMBER,
      description: "Confidence in the prediction (0.0 to 1.0).",
    },
    signals: {
      type: Type.OBJECT,
      properties: {
        perplexity_score: { type: Type.NUMBER, description: "Simulated perplexity metric (0-1)." },
        burstiness_score: { type: Type.NUMBER, description: "Simulated burstiness metric (0-1)." },
        stylometry_score: { type: Type.NUMBER, description: "Score based on sentence structure analysis." },
        formatting_flags: {
          type: Type.ARRAY,
          items: { type: Type.STRING },
          description: "Flags like 'perfect_grammar', 'no_typos', 'formulaic_structure'."
        }
      },
      required: ["perplexity_score", "burstiness_score", "stylometry_score", "formatting_flags"]
    },
    explanation: {
      type: Type.STRING,
      description: "A 2-3 sentence technical explanation of why the text was flagged.",
    },
    suspicious_sentences: {
      type: Type.ARRAY,
      items: { type: Type.STRING },
      description: "A list of specific sentences from the input that strongly indicate AI generation."
    }
  },
  required: ["score", "label", "confidence", "signals", "explanation", "suspicious_sentences"]
};

// Retry logic helper
async function retryOperation<T>(operation: () => Promise<T>, retries = 3, delay = 1000): Promise<T> {
  try {
    return await operation();
  } catch (error: any) {
    if (retries <= 0) throw error;
    console.warn(`Text API call failed. Retrying in ${delay}ms... (${retries} attempts left). Error: ${error.message}`);
    await new Promise(resolve => setTimeout(resolve, delay));
    return retryOperation(operation, retries - 1, delay * 2);
  }
}

export const analyzeText = async (text: string): Promise<TextAnalysisResult> => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key is missing");
  }

  const ai = new GoogleGenAI({ apiKey });

  // Truncate text if too long for efficient processing in this demo
  const processedText = text.length > 5000 ? text.substring(0, 5000) + "..." : text;

  const prompt = `
    You are an expert NLP forensic analyst. Analyze the following text to determine if it was written by a human or generated by an LLM (AI).
    
    NOTE: The input text may have been extracted from a PDF or document, so ignore headers, footers, page numbers, or disjointed line breaks. Focus on the core linguistic content.
    
    Text to analyze:
    """
    ${processedText}
    """
    
    Perform a multi-signal analysis:
    1. Perplexity & Burstiness: Does the text have uniform complexity (AI) or varied peaks (Human)?
    2. Stylometry: Look for overuse of transition words (e.g., "Moreover", "In conclusion"), perfect grammar, and lack of idiosyncrasies.
    3. Content patterns: Look for refusal patterns, hedging, or generic structuring.
    
    Return a JSON response simulating a forensic report. 
    - 'perplexity_score': High score means LOW perplexity (very predictable, likely AI).
    - 'suspicious_sentences': Extract exact sentences from the text that seem most artificial.
  `;

  try {
    const resultText = await retryOperation(async () => {
      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: { parts: [{ text: prompt }] },
        config: {
          responseMimeType: "application/json",
          responseSchema: TEXT_ANALYSIS_SCHEMA,
        }
      });
      if (!response.text) throw new Error("No response from model");
      return response.text;
    });

    const parsed = JSON.parse(resultText);

    return {
      id: crypto.randomUUID(),
      score: parsed.score,
      label: parsed.label,
      confidence: parsed.confidence,
      signals: parsed.signals,
      explanation: parsed.explanation,
      model_version: "v1.0.0-transformer-ensemble",
      timestamp: new Date().toISOString(),
      suspicious_sentences: parsed.suspicious_sentences || [],
      analyzed_text: text
    };

  } catch (error) {
    console.error("Text analysis failed:", error);
    throw error;
  }
};
